import Header from "./Header/page"
import './main.css'
import Tap from "./fff"
import Yes from "./to/yes"

export const metadata = {
  title: 'Next',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <Yes/>
      <Tap>{children}</Tap>
      </body>
    </html>
  )
}
